name: Keep-Alive
on:
  schedule:
    - cron: '*/8 * * * *' # Каждые 8 минут
  workflow_dispatch: # ← Это добавит кнопку "Run workflow"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://cs-observer.onrender.com
